# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.CharField(max_length=50)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picapp.Category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picapp.Location')),
            ],
        ),
    ]
